---
layout: post
title: java通过 url.openStream()访问tornado报 Connection reset by peer问题解决
---

服务端: ubuntu + tornado python2.6

试用java访问服务端.代码如下:

    String strUrl = "http://10.0.0.9:8899/";
    URL url = new URL(strUrl);
    InputStream in = url.openStream();
    BufferedReader br = new BufferedReader(new InputStreamReader(in, "utf-8"));
    String s = null;
    StringBuilder sb = new StringBuilder();
    while ((s = br.readLine()) != null) {
         sb.append(s).append("\n");
    }
    System.out.println(sb.toString());

服务端报错如下:

    [W 130325 01:25:09 iostream:426] Read error on 11: [Errno 104] Connection reset by peer
    [W 130325 01:25:09 iostream:360] error on read
        Traceback (most recent call last):
          File "/usr/local/lib/python2.6/dist-packages/tornado-2.4-py2.6.egg/tornado/iostream.py", line 355, in _handle_read
            if self._read_to_buffer() == 0:
          File "/usr/local/lib/python2.6/dist-packages/tornado-2.4-py2.6.egg/tornado/iostream.py", line 422, in _read_to_buffer
            chunk = self._read_from_socket()
          File "/usr/local/lib/python2.6/dist-packages/tornado-2.4-py2.6.egg/tornado/iostream.py", line 403, in _read_from_socket
            chunk = self.socket.recv(self.read_chunk_size)
        error: [Errno 104] Connection reset by peer

而使用浏览器不会报上述错误

也有人提过类似的问题
<http://stackoverflow.com/questions/12348240/tornados-warning-errno-104-connection-reset-by-peer>


参考(在这篇文章中可以找到解决方案):
<http://comments.gmane.org/gmane.comp.python.tornado/4033>

在这找到了解决方案:
在试用java的HttpURLConnection发送请求的时候加上下面请求头, 问题就可以解决了:

    Connection: close